version: '2'
networks:
  net1:
services:
  haproxy:
    image: haproxy:2.0
    volumes:
      - "./haproxy:/usr/local/etc/haproxy"
    ports:
      - 80:80
      - 81:81
      - 8384:8384
      - 22000:22000
    networks:
      - net1
    restart: unless-stopped
    depends_on:
      - "bn-frontend"
      - "bn-backend"
      - "tileserver-gl"
      - "syncthing"

  bn-frontend:
    image: pigeosolutions/bn-frontend:20190813-ccd8377b
    environment:
      HOSTNAME: hydrosatniger.pigeosolutions.fr
    volumes:
    - ./data:/usr/share/nginx/html/static
    restart: unless-stopped
    networks:
      net1:
        aliases:
          - bn-frontend
  bn-backend:
    image: pigeosolutions/bn-backend:20190529-27df19d7
    environment:
      SOURCES_CONFIG_FILE: /conf/sources.ini
      FLASK_CONFIGURATION: staging
      DEFAULT_NEARBY_LIMIT: '10'
    volumes:
    - ./backend/conf:/conf
    - ./data:/mnt/data
    - ./ftp_data:/mnt/ftp_data
    restart: unless-stopped
    networks:
      net1:
        aliases:
          - bn-backend
  tileserver-gl:
    image: klokantech/tileserver-gl:v3
    volumes:
    - ./tileserver-gl:/data
    restart: unless-stopped
    networks:
      net1:
        aliases:
          - tileserver-gl
  ssh:
    image: mopnaej/sshd-compact:latest
    environment:
      SSH_USERS: jpommier:1000:999, ird:1001:999
      PROJECTID: hydroweb-abn
    volumes:
    - ./sshd/config:/etc/ssh
    - ./sshd/authorized_keys:/etc/authorized_keys
    - ./sshd/home:/home
    - ./ftp_data:/ftp_data/
    restart: unless-stopped
    networks:
      net1:
        aliases:
          - ssh
  syncthing:
    image: linuxserver/syncthing
    environment:
      - PGID=999
      - PUID=999
      - UMASK_SET= 002
    volumes:
      - ./ftp_data:/mnt/ftp_data/
      - ./data:/mnt/data/
      - ./syncthing_config:/config
    restart: unless-stopped
    networks:
      net1:
        aliases:
          - syncthing
